apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-r-us
  namespace: argocd
spec:
  destination:
    namespace: notes-r-us
    server: 'https://kubernetes.default.svc'
  source:
    path: ./kubernetes
    repoURL: 'https://github.com/l2dit/NotesRUs'
    targetRevision: HEAD
  project: public-deployments
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
