[package]
name = "notes_r_us"
version = "1.0.0"
edition = "2021"

[dependencies]
poem = { version = "3.0.0", features = ["static-files"] }
poem-openapi = { version = "5.0.0", features = ["swagger-ui"] }
swagger = "6.4.1"
tokio = { version = "1.37.0", features = ["full"] }
