apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw-notes-r-us
spec:
  cluster:
    name: postgresql-notes-r-us

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
