apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: notes-r-us-creds
  namespace: notes-r-us
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
    - secretName: notes-r-us-secrets
      type: Opaque
      data:
        - objectName: email_password # References dbUsername below
          key: email_password # Key within k8s secret for this value
        - objectName: hanko_secret
          key: hanko_secret

  parameters:
    # Vault role name to use during login
    roleName: 'app'
    # Vault address and TLS connection config is normally best configured by the
    # helm chart, but can be overridden per SecretProviderClass:
    # Vault's hostname
    #vaultAddress: 'https://vault:8200'
    # TLS CA certification for validation
    #vaultCACertPath: '/vault/tls/ca.crt'
    objects: |
      - objectName: "email_password"
        secretPath: "notesrus/hanko"
        secretKey: "email_password"
      - objectName: "hanko_secret"
        secretPath: "notesrus/hanko"
        secretKey: "hanko_secret"
    # "objectName" is an alias used within the SecretProviderClass to reference
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.
