name: Build Docker Image

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            docker-target: linux/amd64

          - target: aarch64-unknown-linux-gnu
            docker-target: linux/arm64

    steps:
      - uses: actions/setup-node@v4

      - name: Setup Rust For ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Build To Target {{ matrix.target }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release

      - name: Upload ${{ matrix.target }} Build
        uses: actions/upload-artifact@v4
        with:
          path: ./target/${{ matrix.target }}/debug/notes_r_us
          name: ${{ matrix.docker-target }}-${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Change To Frontend Dir
        run: cd notes_r_us_ui

      - name: NPM Install Dependencies
        run: cd notes_r_us_ui & npm install

      - name: Build Frontend 
        run: cd notes_r_us_ui & npm run build --if-present

      - name: Upload Frontend
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-${{ github.sha }}
          path: ./dist/
  
  docker_build:
    needs: [build-frontend, build-api]
    name: Docker Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm64]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Get The Frontend
        uses: actions/download-artifact@v4
        with:
          name: Frontend-${{ github.sha }}
          path: ./notes_r_us_ui/

      - name: Get The Api
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.architecture }}
          path: ./notes-r-us

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.architecture }}
          push: true
          tags: |
            asskit/notesrus:${{ github.sha }}
            asskit/notesrus:latest
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:latest
          file: ./ci.Dockerfile 
