name: On Push To Master

on:
  push:
    branches:
      - "master"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Change To Frontend Dir
        run: cd notes_r_us_ui

      - name: NPM Install Dependencies
        run: npm ci

      - name: Build Frontend 
        run: npm run build --if-present

      - name: Upload Frontend
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-${{ github.sha }}
          path: ./dist/
  
  docker_build:
    name: Docker Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm/v7, linux/arm64]
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get The Frontend
        uses: actions/download-artifact@v4
        with:
          name: Frontend-${{ github.sha }}
          path: ./notes_r_us_ui/dist/

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.architecture }}
          push: true
          tags: |
            asskit/notesrus:${{ github.sha }}
            asskit/notesrus:latest
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:latest
          file: ./ci.Dockerfile 
